### ISSUE TITLE
Traceback (most recent call last):   File "c:/legion_pro_7_16IRX8H/Software/Python/comTypeError: 'exclusive' is an unknown keyword argument

### ISSUE THREAD

**Issue by petrasvestartas** [compas-dev/compas_view2#163]
**Describe the bug**

I cannot run compas_view2 installed as part of compas_wood, this worked one year ago.
I am running a fresh new Windows OS 11.

```bash
conda create -n wood-dev python=3.8 mpir mpfr boost-cpp eigen=3.4 cgal-cpp=5.5 pybind11 compas compas_view2 --yes
conda activate wood-dev
git clone https://github.com/petrasvestartas/compas_wood
cd compas_wood
pip install -e .

```

After running an example with view2 I get the error mentioned in this thread:
`https://github.com/compas-dev/compas_view2/issues/137`

Then I tried to install viewer through conda. Installation had no error but the same error appeared.
Then I tried to install the PyQt 5 through pip:
`python -m pip install PyQt5`

Now I get this error:
```bash
C:\legion_pro_7_16IRX8H\software\python\compas_wood>C:/Users/petras/.conda/envs/wood-dev/python.exe c:/legion_pro_7_16IRX8H/Software/Python/compas_wood/tests/compas_wood_5_get_connection_zones.py
C:\Users\petras\.conda\envs\wood-dev\lib\site-packages\qtpy\__init__.py:267: RuntimeWarning: Selected binding "pyside2" could not be found, using "pyqt5"
  warnings.warn('Selected binding "{}" could not be found, '

___________________________________start_of_WOOD_____________________________________
CPP 5
______________________________________ 2.01 ms ______________________________________

____________________________________end_of_WOOD______________________________________
Traceback (most recent call last):
  File "c:/legion_pro_7_16IRX8H/Software/Python/compas_wood/tests/compas_wood_5_get_connection_zones.py", line 65, in <module>
    test_connection_detection()
  File "c:/legion_pro_7_16IRX8H/Software/Python/compas_wood/tests/compas_wood_5_get_connection_zones.py", line 62, in test_connection_detection
    display(result_flat_list, None, None, 0.001, 0, 0, 0, False)
  File "c:\legion_pro_7_16irx8h\software\python\compas_wood\src\compas_wood\viewer_helpers.py", line 49, in display
    viewer = App(
  File "C:\Users\petras\.conda\envs\wood-dev\lib\site-packages\compas_view2\app\app.py", line 221, in __init__
    self.init()
  File "C:\Users\petras\.conda\envs\wood-dev\lib\site-packages\compas_view2\app\app.py", line 235, in init
    self._init_menubar(self.config.get("menubar"))
  File "C:\Users\petras\.conda\envs\wood-dev\lib\site-packages\compas_view2\app\app.py", line 770, in _init_menubar
    self._add_menubar_items(items, self.menubar)
  File "C:\Users\petras\.conda\envs\wood-dev\lib\site-packages\compas_view2\app\app.py", line 813, in _add_menubar_items
    self._add_menubar_items(item["items"], menu)
  File "C:\Users\petras\.conda\envs\wood-dev\lib\site-packages\compas_view2\app\app.py", line 815, in _add_menubar_items
    radio = QtWidgets.QActionGroup(self.window, exclusive=True)
TypeError: 'exclusive' is an unknown keyword argument
```

**To Reproduce**

1. install compas_wood following docs depending on OS: https://petrasvestartas.github.io/compas_wood/latest/installation.html
2. run this example: https://petrasvestartas.github.io/compas_wood/latest/examples/compas_wood_5_get_connection_zones.html

**Expected behavior**

You should see this image:
![image](https://user-images.githubusercontent.com/18013985/227801561-21ebf0be-4e8f-4d39-9956-0718b63466d3.png)

- OS: [e.g. iOS] WIndows 11
- Python version - latest
- Python package manager [pip]

**Additional context**

Works on my old Windows 10 pc and old MAC.

**Comment by Licini** [comment]
@petrasvestartas `0.9.2` is now being released to avoid this error. Should be available in few minutes

**Comment by petrasvestartas** [comment]
Thank you:)

**Comment by petrasvestartas** [comment]
Works perfectly:

![image](https://user-images.githubusercontent.com/18013985/227915319-fcabade8-8544-4878-8bbe-d485d64a3038.png)
