### ISSUE TITLE
AttributeError: module 'ryvencore' has no attribute 'Connection'

### ISSUE THREAD

**Issue by zaczhuozhang** [compas-dev/compas_view2#197]
**Describe the bug**

Setting up from new, and found this error.

```bash

Traceback (most recent call last):
  File "c:/tests/obj.py", line 23, in <module>       
    from compas_view2.app import App
  File "C:\Userszz\miniconda3\envs\view2\lib\site-packages\compas_view2\app\__init__.py", line 6, in <module>
    from .app import App  # noqa : F401
  File "C:\Users\miniconda3\envs\view2\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\miniconda3\envs\view2\lib\site-packages\compas_view2\app\app.py", line 44, in <module>
    from compas_view2.flow import Flow
  File "C:\Users\miniconda3\envs\view2\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\miniconda3\envs\view2\lib\site-packages\compas_view2\flow\__init__.py", line 1, in <module>
    from .flow import Flow  # noqa: F401
  File "C:\Users\miniconda3\envs\view2\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\miniconda3\envs\view2\lib\site-packages\compas_view2\flow\flow.py", line 7, in <module>
    class Flow(Graph):
  File "C:\Users\miniconda3\envs\view2\lib\site-packages\compas_view2\flow\flow.py", line 98, in Flow
    ) -> ryvencore.Connection.DataConnection:
AttributeError: module 'ryvencore' has no attribute 'Connection'

```

**Comment by zaczhuozhang** [comment]
specifying the Ryan version to `3.x.x` solved this problem. The documentation and installation guide need to be updated asap to avoid misleading.

**Comment by tomvanmele** [comment]
fyi, for me this ryven thing was a nice experiment but is not a key thing for the viewers...

**Comment by zaczhuozhang** [comment]
> fyi, for me this ryven thing was a nice experiment but is not a key thing for the viewers...
agree. I just note here to avoid people failing the installation.

**Comment by ZacZhangzhuo** [comment]
> specifying the Ryan version to `3.x.x` solved this problem. The documentation and installation guide need to be updated asap to avoid misleading. @ZacZhangzhuo

correct: specify to `0.3.1.4` solved
